// Code generated by protoc-gen-terraform. DO NOT EDIT.
package test

import (
	"context"
	diag "github.com/hashicorp/terraform-plugin-framework/diag"
	tfsdk "github.com/hashicorp/terraform-plugin-framework/tfsdk"
	types "github.com/hashicorp/terraform-plugin-framework/types"
)

// GenSchemaTest2 returns tfsdk.Schema definition for Test2
func GenSchemaTest2(ctx context.Context) (tfsdk.Schema, diag.Diagnostics) {
	return tfsdk.Schema{Attributes: map[string]tfsdk.Attribute{
		"id": {
			Computed: true,
			Type:     types.StringType,
		},
		"str": {
			Description: "Str string field",
			Optional:    true,
			Type:        types.StringType,
		},
	}}, nil
}
