// Copyright 2022 Liam White
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"flag"

	"google.golang.org/protobuf/compiler/protogen"

	"github.com/dave/jennifer/jen"
	"github.com/rs/zerolog"

	"github.com/liamawhite/protoc-gen-terraform/pkg/generate"
)

func main() {
	var flags flag.FlagSet
	loglevel := flags.Int("loglevel", 1, "loglevel available at https://pkg.go.dev/github.com/rs/zerolog@v1.28.0?utm_source=gopls#Level")
	protogen.Options{
		ParamFunc: flags.Set,
	}.Run(func(gen *protogen.Plugin) error {
		zerolog.SetGlobalLevel(zerolog.Level(*loglevel))
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

// generateFile generates a _ascii.pb.go file containing gRPC service definitions.
func generateFile(gen *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + "_terraform.go"

	f := jen.NewFile(string(file.GoPackageName))
	for _, m := range file.Messages {
		generate.Scheme(f, m)
	}

	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-terraform. DO NOT EDIT.")
	g.P(f.GoString())
}
