#!/bin/bash

ROOT=$(git rev-parse --show-toplevel)

# Apply Licenses
go run github.com/liamawhite/licenser@v0.6.0 apply -r "Liam White"

# Misc linters
find ${ROOT} -type f -name '*.go' | xargs \
    go run golang.org/x/tools/cmd/goimports@v0.1.5 -local github.com/liamawhite/protoc-gen-terraform -w

go mod tidy
